kind: pipeline
type: kubernetes
name: receqif

steps:
- name: build and test
  image: rust:1.73
  commands:
  - rustup default nightly
  - cargo build --verbose --all --features docker
  - cargo test --verbose --all --features docker

- name: build docker image
  image: plugins/docker
  settings:
    repo: registry.dhaenuur.home.rayslava.com/receqif
    tags:
    - ${DRONE_COMMIT_SHA:8}
    - latest
    cache_from: "registry.dhaenuur.home.rayslava.com/receqif:latest"
    registry: registry.dhaenuur.home.rayslava.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy service into kubernetes
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_server: https://192.168.88.5:6443
    kubernetes_token:
      from_secret: kubernetes_token
    namespace: receqif
    deployment: receqif-deploy
    repo: registry.dhaenuur.home.rayslava.com/receqif
    container: receqif
    tag: ${DRONE_COMMIT_SHA:8}
    when:
      branch: [ master ]
