kind: pipeline
type: kubernetes
name: receqif

steps:
- name: build and test
  image: rust:1.73
  commands:
  - rustup default nightly
  - cargo build --verbose --all
  - cargo test --verbose --all

- name: build docker image
  image: plugins/docker
  settings:
    repo: registry.dhaenuur.home.rayslava.com/receqif
    tags:
    - latest
    registry: registry.dhaenuur.home.rayslava.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
