[package]
name = "receqif"
version = "0.1.0"
authors = ["Slava Barinov <rayslava@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
qif_generator = "0.1.4"
chrono = "0.4"
pickledb = "0.4.1"
csv = "1.1"
structopt = "0.3"
shellexpand = "2.1"
radix_trie = { version = "0.2", features = ["serde"] }
libc = "0.2"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"

[features]
tv = []